package catalogdb

// pairLabelDefaults bootstraps pair_label_aliases on first run (also offline fallback).
// Runtime source of truth is Postgres; register via POST /admin/catalog/pair-aliases.
var pairLabelDefaults = map[string]PairRef{
	// Breads
	"roti":           {Kind: PairRefDish, ID: "plain-roti"},
	"rotis":          {Kind: PairRefDish, ID: "plain-roti"},
	"chapati":        {Kind: PairRefDish, ID: "chapati"},
	"chapatis":       {Kind: PairRefDish, ID: "chapati"},
	"roti / chapati": {Kind: PairRefDish, ID: "chapati"},
	"roti sabzi":     {Kind: PairRefDish, ID: "plain-roti"},
	"phulka":         {Kind: PairRefDish, ID: "phulka"},
	"paratha":        {Kind: PairRefDish, ID: "tawa-paratha"},
	"laccha paratha": {Kind: PairRefDish, ID: "lachha-paratha"},
	"naan":           {Kind: PairRefDish, ID: "plain-naan"},
	"poori":          {Kind: PairRefDish, ID: "poori"},
	"puri":           {Kind: PairRefDish, ID: "poori"},
	"bhatura":        {Kind: PairRefDish, ID: "bhatura"},
	"bhature":        {Kind: PairRefDish, ID: "bhatura"},
	"luchi":          {Kind: PairRefDish, ID: "luchi"},
	"missi roti":     {Kind: PairRefDish, ID: "missi-roti"},
	"makki di roti":  {Kind: PairRefDish, ID: "makki-di-roti"},
	"makki roti":     {Kind: PairRefDish, ID: "makki-di-roti"},
	"bajra roti":     {Kind: PairRefDish, ID: "bajra-roti"},
	"bhakri":         {Kind: PairRefDish, ID: "plain-bhakri"},
	"jowar roti":     {Kind: PairRefDish, ID: "jowar-bhakri"},
	"thepla":         {Kind: PairRefDish, ID: "methi-thepla"},
	"baati":          {Kind: PairRefDish, ID: "baati"},

	// Beverages — prepared drinks as dishes, not raw leaves/powder
	"tea":            {Kind: PairRefDish, ID: "masala-chai"},
	"chai":           {Kind: PairRefDish, ID: "masala-chai"},
	"masala chai":    {Kind: PairRefDish, ID: "masala-chai"},

	// Rice & grains
	"steamed rice": {Kind: PairRefIngredient, ID: "rice"},
	"plain rice":   {Kind: PairRefIngredient, ID: "rice"},
	"jeera rice":   {Kind: PairRefDish, ID: "jeera-rice"},
	"pulao":        {Kind: PairRefDish, ID: "veg-pulao"},

	// Dal & kadhi
	"dal":       {Kind: PairRefDish, ID: "dal-tadka"},
	"daal":      {Kind: PairRefDish, ID: "dal-tadka"},
	"dal tadka": {Kind: PairRefDish, ID: "dal-tadka"},
	"dal fry":   {Kind: PairRefDish, ID: "dal-fry-restaurant-style"},
	"kadhi":     {Kind: PairRefDish, ID: "punjabi-kadhi"},
	"khichdi":   {Kind: PairRefDish, ID: "masala-khichdi"},
	"upma":      {Kind: PairRefDish, ID: "rava-upma"},
	"mudde":     {Kind: PairRefDish, ID: "ragi-mudde"},

	// Sides & accompaniments
	"sabzi":              {Kind: PairRefDish, ID: "lauki-sabzi"},
	"pickle":             {Kind: PairRefIngredient, ID: "pickle"},
	"raita":              {Kind: PairRefDish, ID: "cucumber-raita"},
	"curd":               {Kind: PairRefIngredient, ID: "curd"},
	"dahi":               {Kind: PairRefIngredient, ID: "curd"},
	"plain curd":         {Kind: PairRefIngredient, ID: "curd"},
	"papad":              {Kind: PairRefIngredient, ID: "papad"},
	"appalam":            {Kind: PairRefIngredient, ID: "papad"},
	"roasted papad":      {Kind: PairRefIngredient, ID: "papad"},
	"salad":              {Kind: PairRefDish, ID: "kachumber-salad"},
	"salan":              {Kind: PairRefDish, ID: "mirchi-ka-salan"},
	"mirchi ka salan":    {Kind: PairRefDish, ID: "mirchi-ka-salan"},
	"thecha":             {Kind: PairRefDish, ID: "thecha"},
	"halwa":              {Kind: PairRefDish, ID: "gajar-halwa"},
	"kachori":            {Kind: PairRefDish, ID: "kachori"},
	"veg manchurian":     {Kind: PairRefDish, ID: "veg-manchurian"},
	"spring rolls":       {Kind: PairRefDish, ID: "spring-rolls"},
	"fried chili":        {Kind: PairRefIngredient, ID: "green_chilli"},
	"coke":               {Kind: PairRefIngredient, ID: "cold_drink"},
	"chutney":            {Kind: PairRefIngredient, ID: "green_chutney"},
	"green chutney":      {Kind: PairRefIngredient, ID: "green_chutney"},
	"green mint chutney": {Kind: PairRefIngredient, ID: "green_chutney"},
	"mint green chutney": {Kind: PairRefIngredient, ID: "green_chutney"},
	"ginger chutney":     {Kind: PairRefIngredient, ID: "ginger"},
	"peanut chutney":     {Kind: PairRefIngredient, ID: "peanut"},
	"sweet tamarind chutney": {Kind: PairRefIngredient, ID: "tamarind_chutney"},
	"tomato-chutney":     {Kind: PairRefIngredient, ID: "tomato_chutney"},
	"sambar":             {Kind: PairRefDish, ID: "mixed-veg-sambar"},
	"rasam":              {Kind: PairRefDish, ID: "tomato-rasam"},
	"saaru":              {Kind: PairRefDish, ID: "tomato-rasam"},
	"dosa":               {Kind: PairRefDish, ID: "plain-dosa"},
	"idli":               {Kind: PairRefDish, ID: "plain-idli"},
	"biryani":            {Kind: PairRefDish, ID: "veg-biryani"},
	"poriyal":            {Kind: PairRefDish, ID: "carrot-beans-poriyal"},
	"parotta":            {Kind: PairRefDish, ID: "tawa-paratha"},
	"kulcha":             {Kind: PairRefDish, ID: "plain-kulcha"},
	"nuts":               {Kind: PairRefIngredient, ID: "mixed_nuts"},
	"soup":               {Kind: PairRefIngredient, ID: "instant_soup"},
	"curry":              {Kind: PairRefDish, ID: "vegetable-stew"},
	"custard":            {Kind: PairRefIngredient, ID: "custard_powder"},
	"bread slices":       {Kind: PairRefIngredient, ID: "bread"},
	"butter pav":         {Kind: PairRefIngredient, ID: "butter"},
	"pita bread":         {Kind: PairRefIngredient, ID: "bread"},
	"garlic bread":       {Kind: PairRefIngredient, ID: "bread"},
	"garlic toast":       {Kind: PairRefIngredient, ID: "bread"},
	"toast":              {Kind: PairRefIngredient, ID: "bread"},
	"onion raita":        {Kind: PairRefDish, ID: "boondi-raita"},
	"onion-salad":        {Kind: PairRefDish, ID: "kachumber-salad"},
	"aloo dum":           {Kind: PairRefDish, ID: "dum-aloo"},
	"begun bhaja":        {Kind: PairRefIngredient, ID: "brinjal"},
	"chilli chicken":     {Kind: PairRefDish, ID: "chilli-chicken"},
	"chopped onions & lemon": {Kind: PairRefIngredient, ID: "onion"},
	"falooda":            {Kind: PairRefDish, ID: "falooda"},
	"fruit":              {Kind: PairRefIngredient, ID: "banana"},
	"papaya sambharo":    {Kind: PairRefIngredient, ID: "papaya"},
	"potato-masala":      {Kind: PairRefIngredient, ID: "potato"},
	"vanilla ice cream":  {Kind: PairRefIngredient, ID: "ice_cream"},
	"vegetables":         {Kind: PairRefIngredient, ID: "frozen_veg"},
}
